// This file was generated by Dashcode from Apple Inc.
// DO NOT EDIT - This file is maintained automatically by Dashcode.
function setupParts() {
    if (setupParts.called) return;
    setupParts.called = true;
    CreateText('helloText', { text: unescape('Hello%2C World!') });
    CreateInfoButton('info', { frontID: 'front', foregroundStyle: 'white', backgroundStyle: 'black', onclick: 'showBack' });
    CreateGlassButton('done', { text: 'Done', onclick: 'showFront' });
    CreateGlassButton('glassbutton', { onclick: 'rundf', text: 'Run' });
    CreateText('text', { text: 'Filter: ' });
    CreateText('text1', { text: 'Units:' });
    CreateInfoButton('infobutton', { foregroundStyle: 'white', frontID: 'front', onclick: 'showBack', backgroundStyle: 'black' });
    CreateShape('roundedRectangleShape', { rightImageWidth: 5, leftImageWidth: 5 });
    CreateText('text5', { text: 'Hot Keys' });
    CreateText('text6', { text: 'CTRL + i' });
    CreateText('text7', { text: 'Return' });
    CreateText('text8', { text: 'information screen (here)' });
    CreateText('text9', { text: 'run widget' });
    CreateText('text2', { text: 'www.codeuniversity.com' });
    CreateText('text4', { text: 'v0.1' });
    CreateText('text10', { text: unescape('FreeDiskO %u00A9 2009 Steve Dickinson') });
    CreateGlassButton('glassbutton1', { onclick: 'clearFilter', text: 'Clear' });
    CreateText('text12', { text: 'CTRL + c' });
    CreateText('text13', { text: 'clear filter' });
    CreateText('text3', { text: 'FreeDiskO' });
    CreateText('text11', { text: 'v0.3' });
}
window.addEventListener('load', setupParts, false);
